Expanded setup to allow unofficial EL clients
dappnode/DAppNodePackage-lighthouse pull request #16
Opened 2022-09-12 08:41 UTC by Nabsku

This allows users to use unofficial EL clients in Lighthouse (for example the public Besu package).

The user has to actively toggle the advanced mode to get a free-text field. Basic is pre-selected.

2022-09-13 08:14 UTC, alexpeterson91 commented on setup-wizard.yml
> +      Set this to **"advanced"** to pass in an arbitrary Execution Client API or leave on **basic** to choose one below.
```suggestion
      Set this to **"advanced"** to pass in an arbitrary Execution Client Engine-API or leave on **basic** to choose one below.
```

2022-09-13 08:16 UTC, alexpeterson91 commented on setup-wizard.yml
> +      If you're using an **unofficial** Execution Client on Dappnode, you might have to enable this option to use that Execution Client in the Engine API settings of Lighthouse.
```suggestion
      Advanced and Development Use Only: Please only enable this option if you are confident you know what you are doing, if you have any doubts, please use the basic setting.
```

2022-09-13 08:18 UTC, alexpeterson91 commented on setup-wizard.yml
> +      You can usually find the Engine API in the Execution Clients Package Info.
```suggestion
      You can find the Engine API in the Execution Client's Package Info.
```

2022-09-13 08:19 UTC, alexpeterson91 requested changes
Check over my review if you think its acceptable, do not merge yet awaiting final approval.

2022-09-13 08:31 UTC, alexpeterson91 commented
dont wanna mention besu yet because i dont want people jumping to install it and think its all 100% good to users are gonna need to rename their volume after deleting the public package and then ssh in and rename the volume to use the DNP and not have to resync, i did that personally not hard but not easy most people dont have root access even if they know how to access the node and basic linux CLI. if theyre using besu or something else they know they need to do something and will find this very helpful.

2022-09-13 14:03 UTC, Nabsku commented
ACK!

2022-09-14 01:08 UTC, alexpeterson91 commented on setup-wizard.yml
>    - title: Execution Client Config Mode
```suggestion
  - id: config_mode
```
despite it not mattering in a yaml Im gonna just keep the style consistent making the id the first entry for each option, just flipping the title and id here before i push to the other clients

2022-09-14 01:10 UTC, alexpeterson91 commented on setup-wizard.yml
>      id: config_mode
```suggestion
    title: Execution Client Selection Configuration Mode
```
again keeping with the preexisting style

2022-09-14 01:12 UTC, alexpeterson91 requested changes
apply my comments to enforce the same code ordering style in the setup wizards

2022-09-14 01:15 UTC, alexpeterson91 approved these changes

2022-09-14 01:16 UTC, merged